name: Android CI

on:
  push:
    branches: 
      - "main"
      - "development"
  pull_request:
    branches: 
      - "main"
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Unit Tests with Coverage
      run: ./gradlew testDebugUnitTest jacocoTestReport --info

    - name: Debug - List build directory
      run: ls -R app/build

    - name: Check Coverage for FactViewModel
      run: |
        REPORT_PATH="app/build/reports/jacoco/jacocoTestReport/html/index.html"
        if [ ! -f "$REPORT_PATH" ]; then
          echo "Coverage report not found at $REPORT_PATH"
          exit 1
        fi

    - name: Upload all reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: all-reports
        path: app/build/reports

    - name: List Coverage Report Directory
      if: failure()
      run: |
        ls -R app/build/reports/jacoco/

    - name: Upload Lint Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/