name: Android CI

on:
  push:
    branches: 
      - "main"
      - "feature/*"
      - "development"
  pull_request:
    branches: 
      - "main"
      - "feature/*"
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Upload Lint Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/