name: Android CI

on:
  push:
    branches: 
      - "main"
      - "development"
  pull_request:
    branches: 
      - "main"
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Unit Tests with Coverage
      run: ./gradlew testDebugUnitTest jacocoTestReport

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: app/build/reports/jacoco/

    - name: Check Coverage for FactViewModel
      run: |
        if [ ! -f app/build/reports/jacoco/jacocoTestReport/html/index.html ]; then
          echo "Coverage report not found. Failing the build."
          exit 1
        fi
        COVERAGE=$(grep -A 4 "jp/speakbuddy/edisonandroidexercise/presentation/fact/FactViewModel" app/build/reports/jacoco/jacocoTestReport/html/index.html | grep -oP '(?<=<td class="ctr2">)[^<]*' | head -n 1)
        echo "Coverage for FactViewModel: $COVERAGE"
        if [ -z "$COVERAGE" ]; then
          echo "Failed to extract coverage. Failing the build."
          exit 1
        fi
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage is below 80%. Failing the build."
          exit 1
        fi

    - name: List Coverage Report Directory
      if: failure()
      run: |
        ls -R app/build/reports/jacoco/

    - name: Upload Lint Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/